// Generated by gencpp from file state_estimator/AddTwoInts.msg
// DO NOT EDIT!


#ifndef STATE_ESTIMATOR_MESSAGE_ADDTWOINTS_H
#define STATE_ESTIMATOR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <state_estimator/AddTwoIntsRequest.h>
#include <state_estimator/AddTwoIntsResponse.h>


namespace state_estimator
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace state_estimator


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::state_estimator::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::state_estimator::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::state_estimator::AddTwoInts > {
  static const char* value()
  {
    return "state_estimator/AddTwoInts";
  }

  static const char* value(const ::state_estimator::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::state_estimator::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::state_estimator::AddTwoInts >
template<>
struct MD5Sum< ::state_estimator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::state_estimator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator::AddTwoIntsRequest> should match
// service_traits::DataType< ::state_estimator::AddTwoInts >
template<>
struct DataType< ::state_estimator::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::state_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::state_estimator::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::state_estimator::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::state_estimator::AddTwoInts >
template<>
struct MD5Sum< ::state_estimator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::state_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::state_estimator::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::state_estimator::AddTwoIntsResponse> should match
// service_traits::DataType< ::state_estimator::AddTwoInts >
template<>
struct DataType< ::state_estimator::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::state_estimator::AddTwoInts >::value();
  }
  static const char* value(const ::state_estimator::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATE_ESTIMATOR_MESSAGE_ADDTWOINTS_H
