// Generated by gencpp from file interface/AddTwoInts.msg
// DO NOT EDIT!


#ifndef INTERFACE_MESSAGE_ADDTWOINTS_H
#define INTERFACE_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <interface/AddTwoIntsRequest.h>
#include <interface/AddTwoIntsResponse.h>


namespace interface
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace interface


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::interface::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::interface::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::interface::AddTwoInts > {
  static const char* value()
  {
    return "interface/AddTwoInts";
  }

  static const char* value(const ::interface::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::interface::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::interface::AddTwoInts >
template<>
struct MD5Sum< ::interface::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::interface::AddTwoInts >::value();
  }
  static const char* value(const ::interface::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::interface::AddTwoIntsRequest> should match
// service_traits::DataType< ::interface::AddTwoInts >
template<>
struct DataType< ::interface::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::interface::AddTwoInts >::value();
  }
  static const char* value(const ::interface::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::interface::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::interface::AddTwoInts >
template<>
struct MD5Sum< ::interface::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::interface::AddTwoInts >::value();
  }
  static const char* value(const ::interface::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::interface::AddTwoIntsResponse> should match
// service_traits::DataType< ::interface::AddTwoInts >
template<>
struct DataType< ::interface::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::interface::AddTwoInts >::value();
  }
  static const char* value(const ::interface::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTERFACE_MESSAGE_ADDTWOINTS_H
