// Generated by gencpp from file map_loader/AddTwoInts.msg
// DO NOT EDIT!


#ifndef MAP_LOADER_MESSAGE_ADDTWOINTS_H
#define MAP_LOADER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <map_loader/AddTwoIntsRequest.h>
#include <map_loader/AddTwoIntsResponse.h>


namespace map_loader
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace map_loader


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_loader::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::map_loader::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::map_loader::AddTwoInts > {
  static const char* value()
  {
    return "map_loader/AddTwoInts";
  }

  static const char* value(const ::map_loader::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::map_loader::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::map_loader::AddTwoInts >
template<>
struct MD5Sum< ::map_loader::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_loader::AddTwoInts >::value();
  }
  static const char* value(const ::map_loader::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_loader::AddTwoIntsRequest> should match
// service_traits::DataType< ::map_loader::AddTwoInts >
template<>
struct DataType< ::map_loader::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::map_loader::AddTwoInts >::value();
  }
  static const char* value(const ::map_loader::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_loader::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::map_loader::AddTwoInts >
template<>
struct MD5Sum< ::map_loader::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_loader::AddTwoInts >::value();
  }
  static const char* value(const ::map_loader::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_loader::AddTwoIntsResponse> should match
// service_traits::DataType< ::map_loader::AddTwoInts >
template<>
struct DataType< ::map_loader::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::map_loader::AddTwoInts >::value();
  }
  static const char* value(const ::map_loader::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_LOADER_MESSAGE_ADDTWOINTS_H
