// Generated by gencpp from file object_detector/AddTwoInts.msg
// DO NOT EDIT!


#ifndef OBJECT_DETECTOR_MESSAGE_ADDTWOINTS_H
#define OBJECT_DETECTOR_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <object_detector/AddTwoIntsRequest.h>
#include <object_detector/AddTwoIntsResponse.h>


namespace object_detector
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace object_detector


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::object_detector::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::object_detector::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::object_detector::AddTwoInts > {
  static const char* value()
  {
    return "object_detector/AddTwoInts";
  }

  static const char* value(const ::object_detector::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::object_detector::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::object_detector::AddTwoInts >
template<>
struct MD5Sum< ::object_detector::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::object_detector::AddTwoInts >::value();
  }
  static const char* value(const ::object_detector::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detector::AddTwoIntsRequest> should match
// service_traits::DataType< ::object_detector::AddTwoInts >
template<>
struct DataType< ::object_detector::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::object_detector::AddTwoInts >::value();
  }
  static const char* value(const ::object_detector::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::object_detector::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::object_detector::AddTwoInts >
template<>
struct MD5Sum< ::object_detector::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::object_detector::AddTwoInts >::value();
  }
  static const char* value(const ::object_detector::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::object_detector::AddTwoIntsResponse> should match
// service_traits::DataType< ::object_detector::AddTwoInts >
template<>
struct DataType< ::object_detector::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::object_detector::AddTwoInts >::value();
  }
  static const char* value(const ::object_detector::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OBJECT_DETECTOR_MESSAGE_ADDTWOINTS_H
