// Generated by gencpp from file lateral_controller/AddTwoInts.msg
// DO NOT EDIT!


#ifndef LATERAL_CONTROLLER_MESSAGE_ADDTWOINTS_H
#define LATERAL_CONTROLLER_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <lateral_controller/AddTwoIntsRequest.h>
#include <lateral_controller/AddTwoIntsResponse.h>


namespace lateral_controller
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace lateral_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::lateral_controller::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::lateral_controller::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::lateral_controller::AddTwoInts > {
  static const char* value()
  {
    return "lateral_controller/AddTwoInts";
  }

  static const char* value(const ::lateral_controller::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::lateral_controller::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::lateral_controller::AddTwoInts >
template<>
struct MD5Sum< ::lateral_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::lateral_controller::AddTwoInts >::value();
  }
  static const char* value(const ::lateral_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::lateral_controller::AddTwoIntsRequest> should match
// service_traits::DataType< ::lateral_controller::AddTwoInts >
template<>
struct DataType< ::lateral_controller::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::lateral_controller::AddTwoInts >::value();
  }
  static const char* value(const ::lateral_controller::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::lateral_controller::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::lateral_controller::AddTwoInts >
template<>
struct MD5Sum< ::lateral_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::lateral_controller::AddTwoInts >::value();
  }
  static const char* value(const ::lateral_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::lateral_controller::AddTwoIntsResponse> should match
// service_traits::DataType< ::lateral_controller::AddTwoInts >
template<>
struct DataType< ::lateral_controller::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::lateral_controller::AddTwoInts >::value();
  }
  static const char* value(const ::lateral_controller::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // LATERAL_CONTROLLER_MESSAGE_ADDTWOINTS_H
